CREATE TABLE `expense` (
  `EXPENSE_ID` int NOT NULL,
  `EXPENSE_NAME` varchar(45) NOT NULL,
  `EXPENSE_PRICE` double NOT NULL,
  PRIMARY KEY (`EXPENSE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
