CREATE TABLE `sevice_expenses` (
  `SERVICE_NUM` int NOT NULL,
  `EXPENSE_ID` int NOT NULL,
  PRIMARY KEY (`SERVICE_NUM`,`EXPENSE_ID`),
  KEY `SERVICE_EXPENSE_NUM_idx` (`EXPENSE_ID`),
  CONSTRAINT `EXPENSES_SERVICE_NUM` FOREIGN KEY (`SERVICE_NUM`) REFERENCES `service` (`SERVICE_NUM`),
  CONSTRAINT `SERVICE_EXPENSE_NUM` FOREIGN KEY (`EXPENSE_ID`) REFERENCES `priceList` (`expenseID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
