CREATE TABLE `service_performers` (
  `PERFORMER_ID` int NOT NULL,
  `SERVICE_NUM` int NOT NULL,
  PRIMARY KEY (`PERFORMER_ID`,`SERVICE_NUM`),
  KEY `PERFORMER_SERVICE_ID_idx` (`SERVICE_NUM`),
  CONSTRAINT `PERFORMER_SERVICE_ID` FOREIGN KEY (`SERVICE_NUM`) REFERENCES `service` (`SERVICE_NUM`),
  CONSTRAINT `SERVICE_PERFORMER_ID` FOREIGN KEY (`PERFORMER_ID`) REFERENCES `performer` (`PERSON_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
