insert into deceased_maritalstatus (deceased_ssn, status_type) values (180204522, 'never married');
insert into deceased_maritalstatus (deceased_ssn, status_type) values (180873100, 'divorced');
insert into deceased_maritalstatus (deceased_ssn, status_type) values (247198126, 'divorced');
insert into deceased_maritalstatus (deceased_ssn, status_type) values (366354014, 'widowed');
insert into deceased_maritalstatus (deceased_ssn, status_type) values (414893537, 'never married');
insert into deceased_maritalstatus (deceased_ssn, status_type) values (475089557, 'widowed');
insert into deceased_maritalstatus (deceased_ssn, status_type) values (477878034, 'widowed');
insert into deceased_maritalstatus (deceased_ssn, status_type) values (479833273, 'never married');
insert into deceased_maritalstatus (deceased_ssn, status_type) values (484369988, 'married');
insert into deceased_maritalstatus (deceased_ssn, status_type) values (499086437, 'never married');
insert into deceased_maritalstatus (deceased_ssn, status_type) values (511212653, 'married');
insert into deceased_maritalstatus (deceased_ssn, status_type) values (523305340, 'widowed');
insert into deceased_maritalstatus (deceased_ssn, status_type) values (530129843, 'widowed');
insert into deceased_maritalstatus (deceased_ssn, status_type) values (535082922, 'married');
insert into deceased_maritalstatus (deceased_ssn, status_type) values (540256462, 'widowed');
insert into deceased_maritalstatus (deceased_ssn, status_type) values (548603004, 'never married');
insert into deceased_maritalstatus (deceased_ssn, status_type) values (549953897, 'married');
insert into deceased_maritalstatus (deceased_ssn, status_type) values (598977541, 'never married');
insert into deceased_maritalstatus (deceased_ssn, status_type) values (610839355, 'divorced');
insert into deceased_maritalstatus (deceased_ssn, status_type) values (649557167, 'married');
insert into deceased_maritalstatus (deceased_ssn, status_type) values (666515876, 'divorced');
insert into deceased_maritalstatus (deceased_ssn, status_type) values (693122385, 'married');
insert into deceased_maritalstatus (deceased_ssn, status_type) values (707510958, 'married');
insert into deceased_maritalstatus (deceased_ssn, status_type) values (712215845, 'never married');
insert into deceased_maritalstatus (deceased_ssn, status_type) values (717972363, 'divorced');
insert into deceased_maritalstatus (deceased_ssn, status_type) values (800598638, 'divorced');
insert into deceased_maritalstatus (deceased_ssn, status_type) values (816803655, 'married');
insert into deceased_maritalstatus (deceased_ssn, status_type) values (951828891, 'never married');
insert into deceased_maritalstatus (deceased_ssn, status_type) values (958618729, 'married');
insert into deceased_maritalstatus (deceased_ssn, status_type) values (987659961, 'divorced');
insert into deceased_maritalstatus (deceased_ssn, status_type) values (540256462, 'married');
insert into deceased_maritalstatus (deceased_ssn, status_type) values (247198126, 'married');
insert into deceased_maritalstatus (deceased_ssn, status_type) values (477878034, 'divorced');
insert into deceased_maritalstatus (deceased_ssn, status_type) values (484369988, 'divorced');
insert into deceased_maritalstatus (deceased_ssn, status_type) values (511212653, 'widowed');
insert into deceased_maritalstatus (deceased_ssn, status_type) values (523305340, 'divorced');
insert into deceased_maritalstatus (deceased_ssn, status_type) values (530129843, 'divorced');
insert into deceased_maritalstatus (deceased_ssn, status_type) values (535082922, 'widowed');


