insert into service_person (person_id, service_num, role, price) values (1, 0, 'Officiating Clergy', 200.00);
insert into service_person (person_id, service_num, role, price) values (7, 0, 'Officiating Clergy', 200.00);
insert into service_person (person_id, service_num, role, price) values (9, 0, 'Officiating Clergy', 200.00);
insert into service_person (person_id, service_num, role, price) values (2, 6, 'Assisstant', 100.48);
insert into service_person (person_id, service_num, role, price) values (1, 6, 'Assisstant', 100.48);
insert into service_person (person_id, service_num, role, price) values (9, 8, 'Piano', 150.91);
insert into service_person (person_id, service_num, role, price) values (8, 8, 'Piano', 150.91);
insert into service_person (person_id, service_num, role, price) values (3, 8, 'Piano', 150.91);
insert into service_person (person_id, service_num, role, price) values (4, 9, 'Organ', 230.99);
insert into service_person (person_id, service_num, role, price) values (5, 5, 'Solo', 200.01);
insert into service_person (person_id, service_num, role, price) values (6, 2, 'Pall Bearer', 267.00);
insert into service_person (person_id, service_num, role, price) values (7, 9, 'Honorary Pall Bearer', 0.00);
insert into service_person (person_id, service_num, role, price) values (8, 29, 'Officiating Clergy', 125.50);
insert into service_person (person_id, service_num, role, price) values (9, 29, 'Assisstant', 421.00);
insert into service_person (person_id, service_num, role, price) values (10, 18, 'Piano', 230.90);
insert into service_person (person_id, service_num, role, price) values (11, 27, 'Organ', 159.00);
insert into service_person (person_id, service_num, role, price) values (12, 5, 'Solo', 83.21);
insert into service_person (person_id, service_num, role, price) values (13, 2, 'Pall Bearer', 24.10);
insert into service_person (person_id, service_num, role, price) values (14, 7, 'Honorary Pall Bearer', 80.00);
insert into service_person (person_id, service_num, role, price) values (15, 1, 'Officiating Clergy', 58.00);
insert into service_person (person_id, service_num, role, price) values (16, 3, 'Assisstant', 34.05);
insert into service_person (person_id, service_num, role, price) values (17, 4, 'Piano', 85.21);
insert into service_person (person_id, service_num, role, price) values (18, 10, 'Organ', 13.99);
insert into service_person (person_id, service_num, role, price) values (19, 11, 'Solo', 83.21);
insert into service_person (person_id, service_num, role, price) values (20, 11, 'Solo', 83.21);
insert into service_person (person_id, service_num, role, price) values (10, 11, 'Solo', 83.21);
insert into service_person (person_id, service_num, role, price) values (20, 12, 'Pall Bearer', 20.20);
insert into service_person (person_id, service_num, role, price) values (19, 12, 'Pall Bearer', 20.20);
insert into service_person (person_id, service_num, role, price) values (13, 12, 'Pall Bearer', 20.20);
insert into service_person (person_id, service_num, role, price) values (1, 13, 'Honorary Pall Bearer', 90.90);
insert into service_person (person_id, service_num, role, price) values (6, 13, 'Honorary Pall Bearer', 90.90);
insert into service_person (person_id, service_num, role, price) values (8, 13, 'Honorary Pall Bearer', 90.90);
insert into service_person (person_id, service_num, role, price) values (2, 14, 'Officiating Clergy', 78.27);
insert into service_person (person_id, service_num, role, price) values (8, 14, 'Officiating Clergy', 78.27);
insert into service_person (person_id, service_num, role, price) values (16, 14, 'Officiating Clergy', 78.27);
insert into service_person (person_id, service_num, role, price) values (2, 15, 'Assisstant', 20.00);
insert into service_person (person_id, service_num, role, price) values (20, 15, 'Assisstant', 20.00);
insert into service_person (person_id, service_num, role, price) values (25, 15, 'Assisstant', 20.00);
insert into service_person (person_id, service_num, role, price) values (3, 16, 'Piano', 60.00);
insert into service_person (person_id, service_num, role, price) values (30, 16, 'Piano', 60.00);
insert into service_person (person_id, service_num, role, price) values (27, 16, 'Piano', 60.00);
insert into service_person (person_id, service_num, role, price) values (9, 17, 'Organ', 130.00);
insert into service_person (person_id, service_num, role, price) values (30, 17, 'Organ', 130.00);
insert into service_person (person_id, service_num, role, price) values (20, 17, 'Organ', 130.00);
insert into service_person (person_id, service_num, role, price) values (4, 18, 'Solo', 400.00);
insert into service_person (person_id, service_num, role, price) values (5, 18, 'Solo', 400.00);
insert into service_person (person_id, service_num, role, price) values (19, 18, 'Solo', 400.00);
insert into service_person (person_id, service_num, role, price) values (10, 19, 'Pall Bearer', 0.00);
insert into service_person (person_id, service_num, role, price) values (16, 19, 'Honorary Pall Bearer', 0.00);
insert into service_person (person_id, service_num, role, price) values (6, 20, 'Pall Bearer', 0.00);
insert into service_person (person_id, service_num, role, price) values (7, 21, 'Honorary Pall Bearer', 0.00);
insert into service_person (person_id, service_num, role, price) values (21, 22, 'Honorary Pall Bearer', 0.00);
insert into service_person (person_id, service_num, role, price) values (22, 23, 'Honorary Pall Bearer', 0.00);
insert into service_person (person_id, service_num, role, price) values (23, 24, 'Honorary Pall Bearer', 0.00);
insert into service_person (person_id, service_num, role, price) values (24, 25, 'Honorary Pall Bearer', 0.00);
insert into service_person (person_id, service_num, role, price) values (25, 26, 'Honorary Pall Bearer', 0.00);
insert into service_person (person_id, service_num, role, price) values (26, 27, 'Honorary Pall Bearer', 0.00);
insert into service_person (person_id, service_num, role, price) values (27, 28, 'Honorary Pall Bearer', 0.00);
insert into service_person (person_id, service_num, role, price) values (28, 29, 'Honorary Pall Bearer', 0.00);
insert into service_person (person_id, service_num, role, price) values (29, 29, 'Honorary Pall Bearer', 0.00);
insert into service_person (person_id, service_num, role, price) values (30, 29, 'Honorary Pall Bearer', 0.00);




