CREATE TABLE `relative` (
  `PERSON_ID` int NOT NULL,
  `RELATION` varchar(45) NOT NULL,
  `DECEASEDSSN` int NOT NULL,
  PRIMARY KEY (`PERSON_ID`),
  KEY `SSN_idx` (`DECEASEDSSN`),
  CONSTRAINT `DECEASED_SSN` FOREIGN KEY (`DECEASEDSSN`) REFERENCES `deceased` (`SSN`),
  CONSTRAINT `RELATIVE_PERSON_ID` FOREIGN KEY (`PERSON_ID`) REFERENCES `person` (`PERSON_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
